version: '3'

services:
  node:
    container_name: node
    build: ./docker/node
    ports:
      - 80:8080
    volumes:
      - ./src/frontend:/var/www
    tty: true
    stdin_open: true
    command: /bin/sh

  php:
    container_name: php
    environment:
      TZ: Asia/Tokyo
    build: ./docker/php
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx
    container_name: nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    depends_on:
      - php

  db:
    restart: always
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 15432:5432
    user: postgres
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql
